### ISSUE TITLE
No spin projection?

### ISSUE THREAD

**Issue by nikita-astronaut** [issp-center-dev/mVMC#13]
Dear mVMC team,

I would like to simulate the Hamiltonian with only S_z conserved, but SU(2)--nonsymmetric (only U(1)--symmetric). This means, that the exchange term is multiplied by some lambda != 1. 

Is it possible to switch off completely the S_tot projector in the expert mode? By reading the docs I could not understand if it is really possible.

Setting `NSPGaussLeg    0` leads to the errors of the kind
`warning: VMCMainCal rank:0 sample:999 e=-nan
StcOpt: r[0]=-nan
Error: StcOpt info=1 step=0`

Thanks a lot!

**Comment by tmisawa** [comment]
Dear Nikita Astrakhantsev,

By setting 
```
NSPGaussLeg 1
```
you can switch off the spin projection.

Best,
Takahiro Misawa

**Comment by nikita-astronaut** [comment]
Dear Takahiro

thank you so much! This team is always so helpful.
