### ISSUE TITLE
Complex transition matrix?

### ISSUE THREAD

**Issue by nikita-astronaut** [issp-center-dev/mVMC#14]
Dear mVMC developers,

I am interested if one could include complex hoppings in mVMC. Is that possible?

Best wishes,
Nikita

**Comment by tmisawa** [comment]
Dear Nikita,

Yes. 
You can treat complex hoppings in mVMC.
Please see the following link.

https://issp-center-dev.github.io/mVMC/doc/en/html/expert.html#trans-file-trans-def

Best,
Takahiro Misawa

**Comment by nikita-astronaut** [comment]
Dear Takahiro,

thank you very much.

If so, I have another question. In my problem, I have another quantum number conserved (in addition to spin), let us call it flavour, which can take two values. I wish to consider an equally populates flavours wave function. Is it possible to do such things in mvmc? This requires initialisation of the initial spin configuration, that respects this flavour equal population.

Best wishes,
Nikita

**Comment by tmisawa** [comment]
Dear Nikita

I am sorry for the late response.

I think if you treat equally populate flavour wavefunction,
it is necessary to change the code of mVMC.
If Monte Carlo sampling is restricted in the space 
N_A = N_B (N_A is a number of electrons with flavour A),
you can treat such a situation.

To do so, it is necessary to modify the functions 
"VMCMakeSample" and "makeInitialSample" (or related functions).
   
Best,
Takahiro

**Comment by nikita-astronaut** [comment]
Dear Takahiro,

thank you!
