### ISSUE TITLE
4-point correlation functions?

### ISSUE THREAD

**Issue by nikita-astronaut** [issp-center-dev/mVMC#17]
Dear mVMC developers,

in a recent paper https://arxiv.org/pdf/2005.14142.pdf mVMC was used to compute dimer-dimer correlations order, which is a 4-point spin and 8-point fermion correlation function. 

However, in current public version of mVMC this functionality is absent (at least not mentioned in Documentation). 

Is it possible that 4-point correlations are already available? If not, perhaps you could push this commit (even though probably not very well tested) and briefly explain how to use it?

Thanks a lot!

Best wishes,
Nikita

**Comment by tmisawa** [comment]
Dear Nikita,

We implemented the function that can calculate N-body Green functions 
(GreenFuncN in locgrn.c or GreenFuncN_real in locgrn_real.c) for Sz=0 systems.
By using the function, you can calculate the N-body Green functions.
However, to do so, it is necessary to modify the source codes 
(eg. implementing a proper input/output format). 

Best,
Takahiro Misawa

**Comment by nikita-astronaut** [comment]
Dear Takahiro,

thanks for reaching me out. 

Cal I please ask you to elaborate a little bit, like which files/functions I will need to modify in order to output the N-point green function? For instance, above the definition of N-point GF, you have 2-point GF `GreenFunc2_real` which is only used in the computation of Hamiltonian. So I can not understand how it is used for calculations observables (where is it called to compute observables) ?

Thanks a lot!

Best wishes,
Nikita

**Comment by nikita-astronaut** [comment]
Dear Takahiro,

I have another question. In order to correlate the dimer-dimer order, one also needs to compute off-diagonal sigma-matrices correlations. Currently, in the 2-point Green function, only z-z correlators are possible. 

Is this constraint resolved in the N-point GF implemented in mVMC? Thanks!

Best wishes,
Nikita

**Comment by nikita-astronaut** [comment]
Dear Takahiro,

in the manual it is claimed that the 2-point green function in mVMC can be calculated with any combination of 4 spin indexes \\sigma_0..3, but in the source code the function `GreenFunc2_real` has only 2 spin indexes `s` and `t`. Could you please explain? Thanks a lot!

Best wishes,
Nikita

**Comment by nikita-astronaut** [comment]
I think I got it.
