### ISSUE TITLE
incorrect offdiagonal Green's functions

### ISSUE THREAD

**Issue by ryuikaneko** [issp-center-dev/mVMC#4]
Hi,

I check the physical quantities of several nonmagnetic wave functions (translational invariant singlet wave functions) and find unexpected behavior.
I attach the minimal code.
[minimal_code.tar.gz](https://github.com/issp-center-dev/mVMC/files/3445038/minimal_code.tar.gz)
As the simplest case, I use the exact wave function (4 sites) of J1-J2 Heisenberg chain at J2/J1=0.5, known as a Majumdar-Ghosh point.
(See, for example, p.6 in https://arxiv.org/abs/0905.4854 .)
Spin projection is turned off on purpose since the wave function is already in the singlet sector.

The ground state should be nonmagnetic but the expectation values
<S_{i}^{+}> = <c_{i,up}^{dagger} c_{i,down}>
<S_{i}^{-}> = <c_{i,down}^{dagger} c_{i,up}>
give nonzero values ~0.5, which results in FM order along the x direction.
Similarly, <S_i^z S_j^z>!=<S_i^x S_j^x>, so the expected SU(2) symmetry is broken.

The calculated energy itself is consistent with the exact result, and the calculated energy variance is exactly 0.

Best,
Ryui Kaneko

**Comment by k-ido** [comment]
mVMC does not support measurements of offdiagonal expectation values in Sz=0.
We will add error messages for such case.
If you want to measure these quantities, please use “SpinGC” mode, where you can perform VMC simulations without Sz = 0 restriction.

**Comment by xrq-phys** [comment]
FYI, The error message was in version 0.2.0 but seems removed after 1.0.0 for compatibility with "SpinGC" calculation.
Non-diagonal one-body Green's function should be always zero if Sz is fixed (as it hops form Sz=0 to Sz=\pm 1). But quantities like <S_i^x S_j^x> can be properly measured within Sz=0 by commuting its terms:
C_i,up A_j,down C_k,down A_l,up = - C_i,up A_l,up C_k,down A_j,down + Delta_{il} Delta_{jk}.
(Here C is creation and A is annihilation operator.)

**Comment by ryuikaneko** [comment]
OK, thanks.
