### ISSUE TITLE
StcOpt Error

### ISSUE THREAD

**Issue by xfzhang-phys** [issp-center-dev/mVMC#48]
Dear mVMC developers,

I'm trying to use mVMC-1.2.0 code. In some of my calculations, mVMC raised `Error: StcOpt info=1 step=XXX` after `warning: VMCMainCal rank:0 sample:XXXX e=-nan`. (PS: There are also some calculations of different interaction parameters that are finished normally)
These calculations are performed on a 6x6x3 Hubbard system, and typically `NVMCSample=1600, NVMCWarmUp=100` are used with 64 cores. Could you give me some advice on how to prevent this error? (BTW, I find sometimes this error can be prevented by using more warm-up steps)
Thanks !

**Comment by tmisawa** [comment]
This kind of error sometimes occurs when the initial state of the wave functions is not good.
If the initial state `|phi_0>` has no overlap between the most real space configurations, i.e., `Pf(x)=<x|phi_0> = 0`,
this kind of error occurs. 
So, please check the initial state used in your calculations.

**Comment by xfzhang-phys** [comment]
Dear Misawa,

Thank you for your reply!
In my calculations, the above error does not raise at the begining of my calculations. It happens after several optimization steps, and I do not specify the initial file besides the `RndSeed`.
Due to this reason, I guess if my warm-up steps are too small to generate a good enough `| phi_0 >` ? In the CPC paper of mVMC, you said each mVMC sampler generates $N_{MC} / N_{sampler}$ real-space configurations. I wonder if it's also right for `NVMCWarmUp` parameter?

**Comment by tmisawa** [comment]
Dear xfzhang-phys,

>In my calculations, the above error does not raise at the begining of my calculations. It happens after several optimization steps, and I do not specify the initial file besides the RndSeed.

Ok. I understand the situation. I think that the origin of the error may be related to the optimization.
By increasing the Monte Carlo sampling (`NVMCSample `), the optimization may become stable and it is expected that the error does not occur.

> I wonder if it's also right for NVMCWarmUp parameter?

Yes. The total Mone Carlo sampling for warmup is given by ` NVMCWarmUp*Nsampler` .
But, in this case, I think that `NVMCWarnUp` is not directly related to this error.

**Comment by xfzhang-phys** [comment]
Thanks a lot for your advice ！
