### ISSUE TITLE
Progress of Optimization: 0 % error

### ISSUE THREAD

**Issue by sinnnnnnn** [issp-center-dev/mVMC#50]
Dear mVMC developers

I'm a beginner to learn mVMC-1.2.0 code. I tried to use the sample in /mVMC-tutorial/HandsOn/2022_1128/Samples/1D_Hubbard, but the following error occurred:

...
Start: Optimize VMC parameters.
Progress of Optimization: 0 %.
{    0,    1}:  On entry to 
{    1,    0}:  On entry to 
{    1,    1}:  On entry to 
{    4,    0}:  On entry to 
{    2,    0}:  On entry to 
{    2,    1}:  On entry to 
{    3,    0}:  On entry to 
{    3,    1}:  On entry to 
{    4,    1}:  On entry to 
DESCINIT parameter number    7 had an illegal value 
DESCINIT parameter number    7 had an illegal value 
...

How do I deal with the problem?
Thanks!

**Comment by tmisawa** [comment]
Thank you for your interest in mVMC!

In the following link, you can find the tutorial document.

https://www.pasums.issp.u-tokyo.ac.jp/mvmc/wp-content/uploads/sites/5/2022/11/mVMC_problem.pdf

On page 17, there is an explanation (yellow box) of how to perform the mVMC calculation
for the 1D Hubbard model.
Could you tell me where the error occurred in this procedure?

**Comment by sinnnnnnn** [comment]
Thanks for your reply. 
Because I want to use a supercomputer to run the mVMC code, I need to write a ‘job.sh‘ file to submit the task. There seems to be something different with the document.
First, I write ‘srun vmcdry.out stan_opt.in’ in the ‘job.sh’ file, and submit the task to the supercomputer (using ‘sbatch job.sh’). Then the ‘namelist.def’ and other .def files are created successfully. 
Second, I write ‘srun vmc.out namelist.def’ and submit the ‘job.sh’ to the supercomputer. In the output file, an error (“DESCINIT parameter number 7 had an illegal value” like above) occurred and the task was killed. Is there anything wrong?

**Comment by sinnnnnnn** [comment]
Dear Misawa
I tried to run the code on my PC. There is no error this time. I think there were some mistakes during the installation of mVMC on the supercomputer. I will contact the staff of our supercomputer to deal with this issue.
Thank you very much!

**Comment by tmisawa** [comment]
I'm glad to hear that mVMC worked fine on your PC. 
I am guessing from the error message that the origin of the error is probably related to Lapack or ScaLapack.
So, it would be a good idea to check whether Lapack or ScaLapack is appropriately installed.
