### ISSUE TITLE
Doping level in bilayer Hubbard model.

### ISSUE THREAD

**Issue by sinnnnnnn** [issp-center-dev/mVMC#51]
Dear developers of mVMC,

I want to use mVMC to calculate the dopped bilayer Hubbard model. In mVMC, we set “ncon” to fix the number of electrons (i.e. the doping level). I have two questions about it.
1.	If the top layer and bottom layer have equal doping levels, is it enough to set ncon to obtain that each layer has nocn/2 electrons? For example, 4x4x2 Hubbard model, we set ncon=28 to obtain a 1/8 hole doping level. Does this mean 14 electrons in each layer?
2.	If the top layer and bottom layer have different doping levels, for example, 4 electrons in the top layer and 12 electrons in the bottom layer. How can I set the input file to achieve my target?

Best wishes

**Comment by k-ido** [comment]
>If the top layer and bottom layer have equal doping levels, is it enough to set ncon to obtain that each layer has nocn/2 electrons? 

No. Ncond is the total number of electrons in the system we specify. mVMC cannot control the number of electrons on each layer.


>For example, 4x4x2 Hubbard model, we set ncon=28 to obtain a 1/8 hole doping level. Does this mean 14 electrons in each layer?

It depends on the Hamiltonian. If the two layers have the same chemical potential and there is no interactions, each layer has Ncond/2. In general, however, such situation cannot be guaranteed.


>If the top layer and bottom layer have different doping levels, for example, 4 electrons in the top layer and 12 electrons in the bottom layer. How can I set the input file to achieve my target?

The current mVMC code does not support the control of the number of electrons on each layer. If you want to change just the doping levels of layers, one way is to vary the chemical potential of each layer.  You can specify the chemical potentials in Trans file. The details of Trans file can be found in the following page. 
https://issp-center-dev.github.io/mVMC/doc/master/en/expert.html#trans-file-trans-def
