### ISSUE TITLE
Hubbard model with complex hopping term

### ISSUE THREAD

**Issue by sinnnnnnn** [issp-center-dev/mVMC#54]
Dear mVMC Developers,

I recently came across the application of mVMC in studying the WSe2 TMD (Transition Metal Dichalcogenides) system, specifically modeled as the Moire Hubbard model on a triangular lattice. I want to replicate some of these findings. A notable difference of this model is that the hopping term (t=e^iΦσ) is a complex number, where the sign of t's imaginary part varies with the spin σ. Initially, to ensure the accuracy of my results, I employed the Exact Diagonalization (ED) method on a 1D Hubbard chain.

First, I used the mVMC standard mode to compute the conventional Hubbard model (where t remains unchanged with spin) and set L=4, t=1.0,0.5, and U=10. It works well, the ground state energy from mVMC is consistent with that from ED.

Next, I modify the input file (trans.def) to implement the Moire Hubbard model. Actually, the following changes were made：

Before：
1     0     0     0         1.000000000000000       0.50000000000000
0     0     1     0         1.000000000000000      -0.50000000000000
0     1     1     1         1.000000000000000       0.50000000000000
1     1     0     1         1.000000000000000      -0.50000000000000
After：
1     0     0     0         1.000000000000000       0.50000000000000
0     0     1     0         1.000000000000000      -0.50000000000000
0     1     1     1         1.000000000000000      -0.50000000000000
1     1     0     1         1.000000000000000       0.50000000000000
However, the energy differs significantly from ED.
I look forward to any insights or suggestions you may have regarding this matter.
Best regards

**Comment by k-ido** [comment]
If the parameter set for which you did not get accurate results is "Before" one, your target system has spin-dependent transfers.
For this case, I recommend that you use  "OrbitalGeneral",  or both "Orbital" and "OrbitalParallel". 
https://issp-center-dev.github.io/mVMC/doc/master/en/expert.html#orbitalparallel-file
https://issp-center-dev.github.io/mVMC/doc/master/en/expert.html#orbitalgeneral-file

"OrbitalGeneral" and "OrbitalParallel" can be generated by specifying "HubbardGC" in standard mode.
https://issp-center-dev.github.io/mVMC/doc/master/en/standard.html

**Comment by sinnnnnnn** [comment]
Dear Ido，
Thanks for your advice! I know how to prepare input files now.

Best Regards
