### ISSUE TITLE
Gauge fixing for the Slater Determinant

### ISSUE THREAD

**Issue by hz-xiaxz** [issp-center-dev/mVMC#68]
Hi All,
Thanks for your great effort in creating this excellent package!
I noticed that the Slater determinant coefficients `f_{ij}` in this package is outputed as variational parameters, and have huge gauging redundancy. 
I'm using VMC to study some gauging fixing mean field theory with Gutzwiller projection. In that case my Slater Determinant comes from a specific gauge fixing mean field Hamiltonian. Is there any solution to specify the slater determinant in this package? 
Thanks a lot!
Xuanzhe Xia
Department of Physics, UCSB

**Comment by tmisawa** [comment]
It is possible to perform gauge fixing by fixing some components of  `f_{ij}`.
For example, fixing `f_{00}` to a specific value (e.g. 1) corresponds to the
gauge fixing. It is possible to fix `f_{ij}` by modifying `orbitalidx.def`.

If you want to perform more complicated gauge fixing (e.g., fixing the product of `f_ij` or similar constraints), it will be necessary to modify the mVMC code.

**Comment by hz-xiaxz** [comment]
Thanks! This solves my problem.
